import {Dimensions, Platform} from 'react-native';
const {width} = Dimensions.get('window');
import DeviceInfo from 'react-native-device-info';
const isTablet = DeviceInfo.isTablet();
import Theme from '../styles/Theme';

const CUSTOM_CLASSES = {
  table: {
    borderBottomWidth: 1,
    borderBottomColor: '#ddd',
  },
  footnote: {
    fontSize: 30,
    // borderTopWidth: 1,
    // borderTopColor: '#333',
    paddingTop: 6,
    lineHeight: 16,
  },
  'header-border': {
    color: '#fff',
    backgroundColor: '#1598D5',
    padding: 8,
    borderTopRightRadius: 50,
    borderBottomRightRadius: 50,
  },
  'table-row': {
    flex: 1,
    flexDirection: 'row',
  },
  'table-header': {
    fontWeight: 'bold',
    width: '30%',
    marginRight: 15,
  },
  'table-body': {
    width: '67%',
  },
  'orange-title': {
    backgroundColor: '#ffe4ca',
    position: 'absolute',
    paddingTop: 0,
    paddingBottom: 0,
    paddingLeft: 20,
    paddingRight: 20,
    borderBottomLeftRadius: 18,
    borderBottomRightRadius: 18,
    borderTopLeftRadius: 0,
    borderTopRightRadius: 0,
    right: 25,
    top: -3,
    height: 25,
  },
  'orange-sub': {
    fontSize: 12,
    top: -8,
    height: 20,
  },
  orange: {
    backgroundColor: '#ffe4ca',
    paddingTop: 10,
    paddingLeft: 15,
    paddingRight: 15,
    paddingBottom: 10,
    marginTop: 15,
    marginBottom: 15,
    borderBottomLeftRadius: 25,
    borderBottomRightRadius: 25,
    borderTopLeftRadius: 0,
    borderTopRightRadius: 25,
  },
  h3: {
    color: '#ffe4ca',
    fontSize: 12,
    borderBottomColor: '#ddd',
    paddingTop: 10,
    paddingLeft: 15,
    paddingRight: 15,
    paddingBottom: 10,
    marginTop: 15,
    marginBottom: 15,
    borderBottomLeftRadius: 25,
    borderBottomRightRadius: 25,
    borderTopLeftRadius: 0,
    borderTopRightRadius: 25,
  },
  blueshade: {
    backgroundColor: '#D3E3F5',
    paddingTop: 10,
    paddingLeft: 15,
    paddingRight: 15,
    paddingBottom: 10,
    marginTop: 15,
    marginBottom: 15,
    borderBottomLeftRadius: 25,
    borderBottomRightRadius: 25,
    borderTopLeftRadius: 0,
    borderTopRightRadius: 25,
  },
  greenshade: {
    backgroundColor: '#ebf1e5',
    paddingTop: 10,
    paddingLeft: 15,
    paddingRight: 15,
    paddingBottom: 10,
    marginTop: 15,
    marginBottom: 15,
    borderBottomLeftRadius: 25,
    borderBottomRightRadius: 25,
    borderTopLeftRadius: 0,
    borderTopRightRadius: 25,
  },
  lightgray: {
    backgroundColor: '#f2f3f8',
    paddingTop: 10,
    paddingLeft: 15,
    paddingRight: 15,
    paddingBottom: 10,
    marginTop: 15,
    marginBottom: 15,
    borderBottomLeftRadius: 25,
    borderBottomRightRadius: 25,
    borderTopLeftRadius: 0,
    borderTopRightRadius: 25,
  },
  violetshade: {
    backgroundColor: '#e9e0f4',
    paddingTop: 10,
    paddingLeft: 15,
    paddingRight: 15,
    paddingBottom: 10,
    marginTop: 15,
    marginBottom: 15,
    borderBottomLeftRadius: 25,
    borderBottomRightRadius: 25,
    borderTopLeftRadius: 0,
    borderTopRightRadius: 25,
  },
  purpleshade: {
    backgroundColor: '#e9e0f4',
    paddingTop: 10,
    paddingLeft: 15,
    paddingRight: 15,
    paddingBottom: 10,
    marginTop: 15,
    marginBottom: 15,
    borderBottomLeftRadius: 25,
    borderBottomRightRadius: 25,
    borderTopLeftRadius: 0,
    borderTopRightRadius: 25,
  },
  abbreviations: {
    borderBottomWidth: 1,
    borderBottomColor: '#ddd',
    flex: 1,
    flexDirection: 'row',
  },
  shorttxt: {
    width: 70,
    marginRight: 10,
  },
  abbrtext: {
    width: width - 98,
  },
  'orange-box': {
    borderWidth: 1,
    borderColor: '#D28F13',
    padding: 5,
    marginBottom: 10,
    marginTop: 10,
    alignSelf: 'flex-start',
    width: width - 40,
  },
  'blue-box': {
    borderWidth: 1,
    borderColor: '#419AD5',
    padding: 5,
    marginBottom: 10,
    marginTop: 10,
    alignSelf: 'flex-start',
    width: width - 40,
  },
  'green-box': {
    borderWidth: 1,
    borderColor: '#8AC34A',
    padding: 5,
    marginBottom: 10,
    marginTop: 10,
    alignSelf: 'flex-start',
    //color: '#b2632c',
    width: width - 40,
  },
  'resource-block': {
    flex: 1,
    flexDirection: width > 700 ? 'row' : 'column',
  },
  'resource-text': {
    flex: 1,
    flexDirection: 'column',
  },
  'center-box': {
    borderWidth: 1,
    borderColor: '#99B5D4',
    backgroundColor: '#99B5D4',
    padding: 10,
    marginBottom: 10,
    marginTop: 10,
    alignSelf: 'center',
    color: '#212429',
    // width: width - 40,
  },
};
const CUSTOM_TAGSSTYLE = {
  p: {
    fontSize: isTablet ? 17 : Platform.OS == 'ios' ? 17 : 18,
    lineHeight: isTablet ? 28 : 25,
    marginTop: 10,
    marginBottom: 10,
    padding: isTablet ? 1 : 0,
    color: '#595959',
    fontFamily: Theme.fonts.regular,
  },
  span: {
    fontFamily: Theme.fonts.regular,
    fontSize: isTablet ? 22 : Platform.OS == 'ios' ? 17 : 18,
    lineHeight: 25,
    marginTop: 10,
    marginBottom: 10,
    padding: 0,
    color: '#595959',
  },
  div: {
    fontFamily: Theme.fonts.regular,
    fontSize: isTablet ? 22 : Platform.OS == 'ios' ? 17 : 18,
    lineHeight: 25,
    padding: 0,
  },
  h4: {
    fontSize: isTablet ? 22 : Platform.OS == 'ios' ? 17 : 18,
    marginTop: 10,
    marginBottom: 10,
  },
  h5: {
    fontSize: isTablet ? 22 : Platform.OS == 'ios' ? 16 : 18,
  },
  h6: {
    fontSize: isTablet ? 22 : Platform.OS == 'ios' ? 16 : 18,
  },
  li: {
    fontFamily: Theme.fonts.regular,
    fontSize: isTablet ? 22 : Platform.OS == 'ios' ? 17 : 18,
    lineHeight: 22,
    marginTop: 0,
    color: '#595959',
    marginBottom: 0,
    paddingBottom: 0,
  },
  ul: {
    left: -10,
    marginBottom: 0,
    marginTop: 10,
  },
  strong: {
    fontFamily: Theme.fonts.medium,
    flexDirection: 'row',
  },
  em: {
    fontFamily:
      Platform.OS == 'ios' ? Theme.fonts.regular : Theme.fonts.custFontItalic,
    fontSize: isTablet ? 22 : Platform.OS == 'ios' ? 17 : 16,
    // fontWeight: 'none',
  },
  a: {
    color: '#03adea',
    textDecorationLine: 'none',
    marginTop: 10,
    marginBottom: 10,
    padding: 0,
    fontFamily: Theme.fonts.regular,
    fontSize: isTablet ? 22 : 17,
  },
  u: {
    fontFamily: Theme.fonts.regular,
    fontSize: isTablet ? 22 : Platform.OS == 'ios' ? 17 : 18,
    textDecorationLine: 'underline',
  },
};

export const RenderHtmlStyles = {
  CUSTOM_CLASSES,
  CUSTOM_TAGSSTYLE,
};
