import { createTypes } from 'reduxsauce'

export default createTypes(`
  START_SYNC
  SYNC_SUCCESS
  SYNC_FAILED
  SET_SYNC_MESSAGE
  SET_SHARED_CONTENT_NODE
  SET_NODE_MAP_DATA
  SET_SWIPE_ARRAY_NODES

  CHECK_VERSION

  FETCH_REQUEST
  FETCH_SUCCESS
  FETCH_FAILURE

  FETCH_VERSION_REQUEST
  FETCH_VERSION_SUCCESS
  FETCH_VERSION_FAILURE

  FETCH_MENU_REQUEST
  FETCH_MENU_SUCCESS
  FETCH_MENU_FAILURE

  FETCH_TAGS_REQUEST
  FETCH_TAGS_SUCCESS
  FETCH_TAGS_FAILURE

  FETCH_SEARCH_REQUEST
  FETCH_SEARCH_SUCCESS
  FETCH_SEARCH_FAILURE

  FETCH_CAROUSEL_REQUEST
  FETCH_CAROUSEL_SUCCESS
  FETCH_CAROUSEL_FAILURE

  FETCH_LANGUAGE_REQUEST
  FETCH_LANGUAGE_SUCCESS
  FETCH_LANGUAGE_FAILURE

  IMPORT_MENU_DATA
  IMPORT_MENU_FAILURE

  IMPORT_TAGS_DATA
  IMPORT_TAGS_FAILURE

  IMPORT_CAROUSEL_DATA
  IMPORT_CAROUSEL_FAILURE

  IMPORT_SEARCH_DATA
  IMPORT_SEARCH_FAILURE

  IMPORT_LANGUAGE_DATA
  IMPORT_LANGUAGE_FAILURE

  IMPORT_VERSION
  IMPORT_CONTENT_FROM_ASSETS

  ADD_FAVOURITE
  REMOVE_FAVOURITE

  REQ_SEARCH_LIST
  SET_SEARCH_LIST
  CLEAR_SEARCH_LIST
`, {});

export const SET_SHARED_CONTENT_NODE = 'SET_SHARED_CONTENT_NODE';